services:
  api-gateway:
    user: root
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${API_PORT:-3000}:3000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config:/app/config
      - ./volumes:/app/volumes
      - ./logs:/app/logs
      - ./sessions:/app/sessions
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - DEFAULT_ADMIN_USER=${DEFAULT_ADMIN_USER}
      - DEFAULT_ADMIN_PASS=${DEFAULT_ADMIN_PASS}
      - DOCKER_SOCKET=/var/run/docker.sock
    networks:
      - whatsapp_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

networks:
  whatsapp_network: