services:
  api-gateway:
    user: root
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
    ports:
      - "${API_PORT:-3000}:3000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config:/app/config
      - ./volumes:/app/volumes
      - ./logs:/app/logs
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - JWT_SECRET=${JWT_SECRET}
      - DOCKER_SOCKET=/var/run/docker.sock
      - WHATSAPP_IMAGE_NAME=whatsapp-multidevice
    networks:
      - whatsapp_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
      - ./logs/nginx:/var/log/nginx
    networks:
      - whatsapp_network
    restart: unless-stopped
    depends_on:
      api-gateway:
        condition: service_healthy

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_SCHEDULE=0 0 2 * * *
      - WATCHTOWER_CLEANUP=true
    networks:
      - whatsapp_network
    restart: unless-stopped

networks:
  whatsapp_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/16

volumes:
  whatsapp_volumes:
    driver: local